/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { NonGuest } from "./NonGuest";
import { NonGuestCountArgs } from "./NonGuestCountArgs";
import { NonGuestFindManyArgs } from "./NonGuestFindManyArgs";
import { NonGuestFindUniqueArgs } from "./NonGuestFindUniqueArgs";
import { DeleteNonGuestArgs } from "./DeleteNonGuestArgs";
import { NonGuestService } from "../nonGuest.service";
@graphql.Resolver(() => NonGuest)
export class NonGuestResolverBase {
  constructor(protected readonly service: NonGuestService) {}

  async _nonGuestsMeta(
    @graphql.Args() args: NonGuestCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [NonGuest])
  async nonGuests(
    @graphql.Args() args: NonGuestFindManyArgs
  ): Promise<NonGuest[]> {
    return this.service.nonGuests(args);
  }

  @graphql.Query(() => NonGuest, { nullable: true })
  async nonGuest(
    @graphql.Args() args: NonGuestFindUniqueArgs
  ): Promise<NonGuest | null> {
    const result = await this.service.nonGuest(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => NonGuest)
  async deleteNonGuest(
    @graphql.Args() args: DeleteNonGuestArgs
  ): Promise<NonGuest | null> {
    try {
      return await this.service.deleteNonGuest(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
