/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CarWash } from "./CarWash";
import { CarWashCountArgs } from "./CarWashCountArgs";
import { CarWashFindManyArgs } from "./CarWashFindManyArgs";
import { CarWashFindUniqueArgs } from "./CarWashFindUniqueArgs";
import { DeleteCarWashArgs } from "./DeleteCarWashArgs";
import { CarWashService } from "../carWash.service";
@graphql.Resolver(() => CarWash)
export class CarWashResolverBase {
  constructor(protected readonly service: CarWashService) {}

  async _carWashesMeta(
    @graphql.Args() args: CarWashCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CarWash])
  async carWashes(
    @graphql.Args() args: CarWashFindManyArgs
  ): Promise<CarWash[]> {
    return this.service.carWashes(args);
  }

  @graphql.Query(() => CarWash, { nullable: true })
  async carWash(
    @graphql.Args() args: CarWashFindUniqueArgs
  ): Promise<CarWash | null> {
    const result = await this.service.carWash(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CarWash)
  async deleteCarWash(
    @graphql.Args() args: DeleteCarWashArgs
  ): Promise<CarWash | null> {
    try {
      return await this.service.deleteCarWash(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
